In [1]:
# imports

from scipy.io import loadmat
import numpy as np

# Pré-carregamento

O bloco a seguir é responsável por carregar todos os dados presentes em cada um dos datasets para a variável

In [2]:
# pré-carregamento

avi_data = list()
for i in range(1,5):
    avi_data.append(loadmat(f"../datasets/avi/single/Sub{i}_singletarget.mat"))
    avi_data.append(loadmat(f"../datasets/avi/single/Sub{i}_singletarget.mat"))

# Extração dos dados

O seguinte bloco é responsável por obter os dados e suas labels

In [4]:
# extração direta dos dados

X = [d['Data'][0][0][1] for d in avi_data]
y = [d['Data'][0][0][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


### Transformação dos dados

Após obter todos os dados, eles serão transformados para uma forma melhor de trabalha-los

In [5]:
X_std = np.array([np.transpose(data) for data in X])
X_std = X_std.reshape(X_std.shape[0]*X_std.shape[1], X_std.shape[2])
y_std = np.array([np.transpose(data) for data in y])
y_std = y_std.reshape(1, y_std.shape[0]*y_std.shape[1])[0]

X_std.shape, y_std.shape

(8, 10, 8192)


((80, 8192), (80,))

### Salvar dados carregados

Para que esse processo não precise ser repetido, os dados serão salvos no formato .npy, que é correspondente a um numpyArray

In [6]:
np.save("../datasets/avi/multi/data_multi.npy", X_std)
np.save("../datasets/avi/multi/labels_multi.npy", y_std)