In [1]:
# imports

from scipy.io import loadmat
import numpy as np

# Pré-carregamento

O bloco a seguir é responsável por carregar todos os dados presentes em cada um dos datasets para a variável

In [2]:
# pré-carregamento

avi_data = list()
for i in range(1,5):
    avi_data.append(loadmat(f"../datasets/avi/multi/Sub{i}_1_multitarget.mat"))
    avi_data.append(loadmat(f"../datasets/avi/multi/Sub{i}_2_multitarget.mat"))

### Visualização dos dados

Essa visualização é apenas para melhor compreensão dos dados que serão utilizados no futuro

In [3]:
print("Valores que não serão uteis:")
[print(avi_data[0]['Data'][0][0][i]) for i in range(7)]
print()
print("Valores que serão uteis:")
print(avi_data[0]['Data'][0][0][7])
print(avi_data[0]['Data'][0][0][8][0])

Valores que não serão uteis:
[[512]]
['1.7 cm']
['60 cm']
['LCD Monitor, Benq XL2420T']
['Oz']
['M']
['32']

Valores que serão uteis:
[[-7.01667796e-06 -7.31038426e-06 -8.57892064e-06 ...  1.64608464e-05
   1.12859943e-05 -5.29669160e-06]
 [-6.67584300e-06 -7.31422551e-06 -7.62318177e-06 ...  1.63658460e-05
   1.00137386e-05 -4.87175521e-06]
 [-6.14027977e-06 -6.84096267e-06 -6.86276917e-06 ...  1.60672698e-05
   8.45984869e-06 -4.22229687e-06]
 ...
 [ 2.28551994e-06  3.31084584e-06 -5.42551106e-06 ...  7.33828983e-06
   5.71450937e-06 -2.08970050e-06]
 [ 2.72940997e-06  3.40825204e-06 -4.40975055e-06 ...  6.20197625e-06
   8.79591880e-06 -2.35789207e-06]
 [ 3.09955794e-06  3.61427783e-06 -3.06295033e-06 ...  4.86804811e-06
   1.13561446e-05 -2.99241083e-06]]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]


# Extração dos dados

O seguinte bloco é responsável por obter os dados e suas labels

In [4]:
# extração direta dos dados

X = [d['Data'][0][0][7] for d in avi_data]
y = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


### Transformação dos dados

Após obter todos os dados, eles serão transformados para uma forma melhor de trabalha-los

In [5]:
X_std = np.array([np.transpose(data) for data in X])
X_std = X_std.reshape(X_std.shape[0]*X_std.shape[1], X_std.shape[2])
y_std = np.array([np.transpose(data) for data in y])
y_std = y_std.reshape(1, y_std.shape[0]*y_std.shape[1])[0]

X_std.shape, y_std.shape

(8, 10, 8192)


((80, 8192), (80,))

### Salvar dados carregados

Para que esse processo não precise ser repetido, os dados serão salvos no formato .npy, que é correspondente a um numpyArray

In [6]:
np.save("../datasets/avi/multi/data_multi.npy", X_std)
np.save("../datasets/avi/multi/labels_multi.npy", y_std)